### ISSUE TITLE
User signup and login flow

### ISSUE THREAD

**Issue by alysivji** [alysivji/street-team#23]
As a user, I want to be able to sign into the street team website with my GitHub account credentials.

### Definition of Done

- [x] Login with GitHub with [python social](https://python-social-auth.readthedocs.io/en/latest/) -- #28 
- [x] Allow user to connect phone number to account
	- figure out the registration and login flow
    - users can only claim number that is not already taken
	- use a state machine
- [x] Store user information
	- profile relation that is 1-1 related to user?
	- github login table?
	- maybe both...

### Things to think about

- do we need to create a separate profile table?
- user can have more than 1 phone number associated with their account

### Todo

- [x] add tests to ensure we can login/logout properly, look into selenium for UI tests
- [x] set up redirect pages for social auth... this will come once we figure out the website
