### ISSUE TITLE
Figure out user management

### ISSUE THREAD

**Issue by alysivji** [alysivji/street-team#6]
As a user, I want to allow users to register for the site. They should be able to link their phone numbers to blah.

Should we use the admin and restrict things based on permission? A separate Django app? Separate views?

Django has built-in views: https://docs.djangoproject.com/en/2.2/topics/auth/default/#module-django.contrib.auth.views

Add a unique UUID to each user
https://docs.djangoproject.com/en/2.2/howto/writing-migrations/#migrations-that-add-unique-fields

Should we have profile information in a separate `Profile` table?

### Resources to Review

- [ ] https://docs.djangoproject.com/en/2.2/topics/auth/
- [ ] https://realpython.com/manage-users-in-django-admin/

**Comment by alysivji** [comment]
## Takeaways

- Need to figure out permissions users need
  - create site admins permission that owns all
  - member permission that allows us to see certain views
- Use [python social's Django integration](https://python-social-auth.readthedocs.io/en/latest/) to only allow login thru GitHub
- add unique field to user table, [docs](https://docs.djangoproject.com/en/2.2/howto/writing-migrations/#migrations-that-add-unique-fields)

## Todo

- [ ] figure out sessions, [docs](https://python-social-auth.readthedocs.io/en/latest/)
